#!/bin/sh

# Generate .bundle/config instead of using env vars or command line
# flags so that we have consistent configuration for our `bundle
# check` and `bundle install` calls here, as well as any manual calls
# to `bundle` that people might make.

rm -rf .bundle
mkdir .bundle

echo "---
BUNDLE_BIN: false
" > .bundle/config

bundle check > /dev/null 2>&1 || bundle install "$@"

echo "
export AWS_ACCESS_KEY_ID=\"ID\"
export AWS_SECRET_ACCESS_KEY=\"SECRET\"
" > .envrc
