#!/bin/sh

# Generate .bundle/config instead of using env vars or command line
# flags so that we have consistent configuration for our `bundle
# check` and `bundle install` calls here, as well as any manual calls
# to `bundle` that people might make.

rm -rf .bundle
mkdir .bundle

echo "---
BUNDLE_BIN: false
" > .bundle/config

bundle check > /dev/null 2>&1 || bundle install "$@"

if [ -f ".envrc" ]; then
  echo ".envrc already exists so skipping"
else
  echo "
  export AWS_ACCESS_KEY_ID=\"ID\"
  export AWS_SECRET_ACCESS_KEY=\"SECRET\"
  export AWS_BUCKET_ID=\"s3://\"
  export AWS_DISTRIBUTION_ID=\"ID\"

  if [ -x \"$(command -v nix)\" ] && [ \"$(type -t use_nix)\" = function ]; then
    use_nix
  fi
  " > .envrc
fi
